---
services:
  coredns:
    image: coredns/coredns:1.11.1
    working_dir: /etc/coredns
    volumes:
      - ./coredns:/etc/coredns/:ro
  dnsdist:
    image: powerdns/dnsdist-19:1.9.3
    ports:
      - "53:53/udp"
    volumes:
      - ./dnsdist/dnsdist.conf:/etc/dnsdist/dnsdist.conf:ro
